---
- name: test-playbook-2
  hosts: stg
  gather_facts: no
  tasks:
    - name: this
      debug:
        msg: this

    - pause:
        seconds: "{{ pause_seconds }}"
      when: pause | default(false)

    - name: that
      debug:
        msg: that

    - pause:
        seconds: "{{ pause_seconds }}"
      when: pause | default(false)

    - name: the other
      debug:
        msg: the other
